databases:
  - name: devopsappdb
    plan: free
    databaseName: devopsapp
    user: devopsapp

services:
  - type: web
    plan: free
    name: devopsapp
    runtime: python
    buildCommand: |
      pip install coverage
      coverage run -m pytest
      coverage report
      coverage report --fail-under=80  # Set the minimum coverage threshold to 80%
      ./build.sh
    startCommand: |
      python -c "import os; from django.contrib.auth.models import User; username = os.getenv('DJANGO_SUPERUSER_USERNAME'); password = os.getenv('DJANGO_SUPERUSER_PASSWORD'); User.objects.create_superuser(username, 'admin@example.com', password) if not User.objects.filter(username=username).exists() else None"
      python -m gunicorn devopsproject.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devopsappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
