databases:
  - name: devopsappdb
    plan: free
    databaseName: devopsapp
    user: devopsapp

services:
  - type: web
    plan: free
    name: devopsapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn devopsproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devopsappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    preDeploy:
    - command: "pip install coverage"
    - command: "coverage run -m pytest"
    - command: "coverage report"
    - command: "coverage report --fail-under=80"  # Set the minimum coverage threshold to 80%